# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

services:
  ###########################
  # Setup the Nginx container
  ###########################
  nginx-auth:
    image: nginx:latest
    container_name: auth-webserver
    working_dir: /etc/nginx
    ports:
      - 2803:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  ###########################
  # Setup the PHP container
  ###########################
  php-auth:
    build: ./docker/php/
    container_name: auth-php
    working_dir: /var/www/auth
    expose:
      - 9000
    volumes:
      - .:/var/www/auth

  ###########################
  # Setup the Database (MySQL) container
  ###########################
#  mysql:
#    image: mysql:latest
#    ports:
#      - 6603:3306
#    volumes:
#      - database_data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_DATABASE: web_services
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
